# Generated by Django 6.0.6 on 2026-06-20 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('sports', 'Sports & Games'), ('wellness', 'Wellness & Team Development')], default='sports', max_length=20)),
                ('name', models.CharField(help_text="e.g. 'Sports Experiences', 'Stress Management'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Catalogue categories',
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_live', models.BooleanField(default=False, help_text='Checked = currently operating here.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=120)),
                ('work_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('employee_count', models.CharField(blank=True, choices=[('1-50', '1–50'), ('51-150', '51–150'), ('151-500', '151–500'), ('500+', '500+')], max_length=20)),
                ('interested_annual_calendar', models.BooleanField(default=False, verbose_name='Annual Sports Calendar')),
                ('interested_tournaments', models.BooleanField(default=False, verbose_name='Tournaments / Leagues')),
                ('interested_wellness', models.BooleanField(default=False, verbose_name='Wellness Sessions')),
                ('interested_custom', models.BooleanField(default=False, verbose_name='Custom Program')),
                ('message', models.TextField(blank=True, verbose_name='Anything we should know?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False, help_text="Mark once you've followed up.")),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Spark, League Pro, Enterprise', max_length=80)),
                ('badge_label', models.CharField(help_text="Small label above the title, e.g. 'Starter', 'Most Popular', 'Enterprise'", max_length=40)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured plan gets the red highlighted card style.')),
                ('description', models.TextField(help_text='1-2 sentence description shown under the title.')),
                ('cta_label', models.CharField(default='Get a Quote', max_length=40)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first (left to right).')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(help_text="e.g. 'HR Manager · IT Company, Hyderabad'", max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Out of 5 stars')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketing.cataloguecategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='marketing.package')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
